[[theme]]
name = "kittycafe-sm"
repository = "https://github.com/etrigan63/kittycafe-sm"
commit = "*"
version = "2.3.2"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "kittycafe-dm"
repository = "https://github.com/etrigan63/kittycafe-dm"
commit = "*"
version = "2.3.2"
leftwm_versions = ">=0.3.0"